name: Generate Snake Game Contribution Grid
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:

permissions:
  contents: write  # ✅ This grants write access to push files

jobs:
  generate:
    runs-on: ubuntu-22.04  # ✅ Force using Ubuntu 22.04 instead of latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "mr.unknown5264@gmail.com"
          git config --global user.name "mr-attique-developer"

      - name: Generate Snake Animation
        run: mkdir -p dist && touch dist/github-contribution-grid-snake.svg

      - name: Commit and Push if Changes Exist
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Updated snake contribution graph"
            git push
          else
            echo "No changes to commit"
          fi
